"""initial_schema

Revision ID: 3cea8a7c3e9b
Revises: 
Create Date: 2026-06-05 23:20:44.873403
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '3cea8a7c3e9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.schema.CreateSequence(sa.Sequence('global_sync_version_seq')))
    op.create_table('chambers',
    sa.Column('chamber_type', sa.Enum('DEPUTIES', 'SENATE', name='chamber_type', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chambers')),
    sa.UniqueConstraint('chamber_type', name=op.f('uq_chambers_chamber_type'))
    )
    op.create_index(op.f('ix_chambers_deleted_at'), 'chambers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_chambers_sync_version'), 'chambers', ['sync_version'], unique=False)
    op.create_table('change_logs',
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('change_type', sa.Text(), nullable=False),
    sa.Column('sync_version', sa.BigInteger(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_fields', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_logs'))
    )
    op.create_index(op.f('ix_change_logs_entity_id'), 'change_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_change_logs_entity_type'), 'change_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_change_logs_sync_version'), 'change_logs', ['sync_version'], unique=False)
    op.create_table('circumscriptions',
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_circumscriptions')),
    sa.UniqueConstraint('number', name=op.f('uq_circumscriptions_number'))
    )
    op.create_index(op.f('ix_circumscriptions_deleted_at'), 'circumscriptions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_circumscriptions_sync_version'), 'circumscriptions', ['sync_version'], unique=False)
    op.create_table('client_sync_states',
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('last_sync_version', sa.BigInteger(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_sync_states')),
    sa.UniqueConstraint('device_id', 'entity_type', name='uq_client_sync_states_device_entity')
    )
    op.create_index(op.f('ix_client_sync_states_device_id'), 'client_sync_states', ['device_id'], unique=False)
    op.create_index(op.f('ix_client_sync_states_entity_type'), 'client_sync_states', ['entity_type'], unique=False)
    op.create_table('coalitions',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('abbreviation', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coalitions'))
    )
    op.create_index(op.f('ix_coalitions_deleted_at'), 'coalitions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_coalitions_sync_version'), 'coalitions', ['sync_version'], unique=False)
    op.create_table('ingestor_state',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('last_sync_date', sa.Date(), nullable=True),
    sa.Column('last_cursor', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestor_state')),
    sa.UniqueConstraint('entity_type', name=op.f('uq_ingestor_state_entity_type'))
    )
    op.create_table('legislative_periods',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legislative_periods')),
    sa.UniqueConstraint('number', name=op.f('uq_legislative_periods_number'))
    )
    op.create_index(op.f('ix_legislative_periods_deleted_at'), 'legislative_periods', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_legislative_periods_sync_version'), 'legislative_periods', ['sync_version'], unique=False)
    op.create_table('official_gazette_norms',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('edition', sa.Text(), nullable=True),
    sa.Column('branch', sa.Text(), nullable=True),
    sa.Column('ministry', sa.Text(), nullable=True),
    sa.Column('organ', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('cve', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), server_default='', nullable=False),
    sa.Column('titulo_amigable', sa.Text(), nullable=True),
    sa.Column('resumen_ejecutivo', sa.Text(), nullable=True),
    sa.Column('puntos_clave', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('beneficiarios', sa.Text(), nullable=True),
    sa.Column('categoria_ia', sa.Text(), nullable=True),
    sa.Column('importancia_ciudadana', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_official_gazette_norms')),
    sa.UniqueConstraint('cve', name=op.f('uq_official_gazette_norms_cve'))
    )
    op.create_index(op.f('ix_official_gazette_norms_deleted_at'), 'official_gazette_norms', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_official_gazette_norms_sync_version'), 'official_gazette_norms', ['sync_version'], unique=False)
    op.create_table('political_parties',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_political_parties')),
    sa.UniqueConstraint('abbreviation', name=op.f('uq_political_parties_abbreviation'))
    )
    op.create_index(op.f('ix_political_parties_deleted_at'), 'political_parties', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_political_parties_sync_version'), 'political_parties', ['sync_version'], unique=False)
    op.create_table('regions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('capital', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('number', name=op.f('uq_regions_number'))
    )
    op.create_index(op.f('ix_regions_deleted_at'), 'regions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_regions_sync_version'), 'regions', ['sync_version'], unique=False)
    op.create_table('regulations',
    sa.Column('numero', sa.Text(), nullable=False),
    sa.Column('anio', sa.Text(), nullable=False),
    sa.Column('ministerio', sa.Text(), nullable=False),
    sa.Column('subsecretaria', sa.Text(), nullable=True),
    sa.Column('materia', sa.Text(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('estado', sa.Text(), nullable=True),
    sa.Column('categoria', sa.Text(), nullable=False),
    sa.Column('reingresado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulations')),
    sa.UniqueConstraint('numero', 'anio', 'ministerio', 'categoria', name='uq_regulations_natural_key')
    )
    op.create_index(op.f('ix_regulations_content_fingerprint'), 'regulations', ['content_fingerprint'], unique=False)
    op.create_index(op.f('ix_regulations_deleted_at'), 'regulations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_regulations_sync_version'), 'regulations', ['sync_version'], unique=False)
    op.create_table('topics',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], name=op.f('fk_topics_parent_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('name', name=op.f('uq_topics_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_topics_slug'))
    )
    op.create_index(op.f('ix_topics_deleted_at'), 'topics', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_topics_sync_version'), 'topics', ['sync_version'], unique=False)
    op.create_table('voting_window_aggregates',
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voting_window_aggregates')),
    sa.UniqueConstraint('window_days', name='uq_voting_window_aggregates_window')
    )
    op.create_index(op.f('ix_voting_window_aggregates_deleted_at'), 'voting_window_aggregates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_voting_window_aggregates_sync_version'), 'voting_window_aggregates', ['sync_version'], unique=False)
    op.create_table('bloc_affiliations',
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.Column('bloc', sa.Enum('OFICIALISMO', 'OPOSICION', name='bloc', native_enum=False), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['political_parties.id'], name=op.f('fk_bloc_affiliations_party_id_political_parties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bloc_affiliations')),
    sa.UniqueConstraint('party_id', 'start_date', name='uq_bloc_affiliations_party_start')
    )
    op.create_index(op.f('ix_bloc_affiliations_deleted_at'), 'bloc_affiliations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bloc_affiliations_sync_version'), 'bloc_affiliations', ['sync_version'], unique=False)
    op.create_table('circumscription_regions',
    sa.Column('circumscription_id', sa.BigInteger(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['circumscription_id'], ['circumscriptions.id'], name=op.f('fk_circumscription_regions_circumscription_id_circumscriptions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_circumscription_regions_region_id_regions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('circumscription_id', 'region_id', name=op.f('pk_circumscription_regions'))
    )
    op.create_table('coalition_memberships',
    sa.Column('coalition_id', sa.BigInteger(), nullable=False),
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=False),
    sa.Column('left_date', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['coalition_id'], ['coalitions.id'], name=op.f('fk_coalition_memberships_coalition_id_coalitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['political_parties.id'], name=op.f('fk_coalition_memberships_party_id_political_parties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coalition_memberships')),
    sa.UniqueConstraint('coalition_id', 'party_id', 'joined_date', name='uq_coalition_memberships_membership')
    )
    op.create_index(op.f('ix_coalition_memberships_deleted_at'), 'coalition_memberships', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_coalition_memberships_sync_version'), 'coalition_memberships', ['sync_version'], unique=False)
    op.create_table('committees',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('chamber_id', sa.BigInteger(), nullable=True),
    sa.Column('committee_type', sa.Enum('PERMANENT', 'SPECIAL', 'INVESTIGATIVE', 'MIXED', name='committee_type', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['chamber_id'], ['chambers.id'], name=op.f('fk_committees_chamber_id_chambers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_committees'))
    )
    op.create_index(op.f('ix_committees_deleted_at'), 'committees', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_committees_sync_version'), 'committees', ['sync_version'], unique=False)
    op.create_table('districts',
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_districts_region_id_regions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts')),
    sa.UniqueConstraint('number', name=op.f('uq_districts_number'))
    )
    op.create_index(op.f('ix_districts_deleted_at'), 'districts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_districts_sync_version'), 'districts', ['sync_version'], unique=False)
    op.create_table('legislative_sessions',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=30), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('chamber_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['chamber_id'], ['chambers.id'], name=op.f('fk_legislative_sessions_chamber_id_chambers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['period_id'], ['legislative_periods.id'], name=op.f('fk_legislative_sessions_period_id_legislative_periods'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legislative_sessions'))
    )
    op.create_index(op.f('ix_legislative_sessions_deleted_at'), 'legislative_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_legislative_sessions_sync_version'), 'legislative_sessions', ['sync_version'], unique=False)
    op.create_table('provinces',
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_provinces_region_id_regions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provinces')),
    sa.UniqueConstraint('number', name=op.f('uq_provinces_number'))
    )
    op.create_index(op.f('ix_provinces_deleted_at'), 'provinces', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_provinces_sync_version'), 'provinces', ['sync_version'], unique=False)
    op.create_table('regulation_stages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('reglamento_id', sa.BigInteger(), nullable=False),
    sa.Column('etapa', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('accion', sa.Text(), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('documento', sa.Text(), nullable=True),
    sa.Column('documento_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reglamento_id'], ['regulations.id'], name=op.f('fk_regulation_stages_reglamento_id_regulations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulation_stages'))
    )
    op.create_table('bills',
    sa.Column('bcn_id', sa.String(length=50), nullable=True),
    sa.Column('bulletin_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('bill_type', sa.Enum('PROJECT', name='bill_type', native_enum=False), nullable=False),
    sa.Column('origin', sa.Enum('EXECUTIVE', 'DEPUTIES', name='bill_origin', native_enum=False), nullable=False),
    sa.Column('origin_chamber_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ARCHIVED', 'WITHDRAWN', 'UNCONSTITUTIONAL', 'ENACTED', 'PUBLISHED', name='bill_status', native_enum=False), nullable=False),
    sa.Column('current_chamber_id', sa.BigInteger(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('law_number', sa.String(length=50), nullable=True),
    sa.Column('current_committee_id', sa.BigInteger(), nullable=True),
    sa.Column('full_text_url', sa.String(length=500), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_summary_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['current_chamber_id'], ['chambers.id'], name=op.f('fk_bills_current_chamber_id_chambers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_committee_id'], ['committees.id'], name=op.f('fk_bills_current_committee_id_committees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_chamber_id'], ['chambers.id'], name=op.f('fk_bills_origin_chamber_id_chambers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bills')),
    sa.UniqueConstraint('bcn_id', name=op.f('uq_bills_bcn_id')),
    sa.UniqueConstraint('bulletin_number', name=op.f('uq_bills_bulletin_number'))
    )
    op.create_index(op.f('ix_bills_deleted_at'), 'bills', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bills_sync_version'), 'bills', ['sync_version'], unique=False)
    op.create_table('communes',
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('province_id', sa.BigInteger(), nullable=True),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=True),
    sa.Column('circumscription_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['circumscription_id'], ['circumscriptions.id'], name=op.f('fk_communes_circumscription_id_circumscriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_communes_district_id_districts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], name=op.f('fk_communes_province_id_provinces'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_communes_region_id_regions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communes')),
    sa.UniqueConstraint('number', name=op.f('uq_communes_number'))
    )
    op.create_index(op.f('ix_communes_deleted_at'), 'communes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_communes_sync_version'), 'communes', ['sync_version'], unique=False)
    op.create_table('legislators',
    sa.Column('bcn_id', sa.String(length=50), nullable=True),
    sa.Column('bcn_uri', sa.String(length=500), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('profession', sa.String(length=200), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('photo_thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('bcn_wiki_url', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('twitter_handle', sa.String(length=50), nullable=True),
    sa.Column('instagram_handle', sa.String(length=50), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('chamber_type', sa.Enum('DEPUTIES', 'SENATE', name='legislator_chamber_type', native_enum=False), nullable=False),
    sa.Column('party_id', sa.BigInteger(), nullable=True),
    sa.Column('district_id', sa.BigInteger(), nullable=True),
    sa.Column('circumscription_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_bloc', sa.Enum('OFICIALISMO', 'OPOSICION', name='legislator_default_bloc', native_enum=False), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['circumscription_id'], ['circumscriptions.id'], name=op.f('fk_legislators_circumscription_id_circumscriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_legislators_district_id_districts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_id'], ['political_parties.id'], name=op.f('fk_legislators_party_id_political_parties'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legislators')),
    sa.UniqueConstraint('bcn_id', name=op.f('uq_legislators_bcn_id')),
    sa.UniqueConstraint('bcn_uri', name=op.f('uq_legislators_bcn_uri'))
    )
    op.create_index(op.f('ix_legislators_deleted_at'), 'legislators', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_legislators_sync_version'), 'legislators', ['sync_version'], unique=False)
    op.create_table('bill_authorships',
    sa.Column('bill_id', sa.BigInteger(), nullable=False),
    sa.Column('legislator_id', sa.BigInteger(), nullable=False),
    sa.Column('author_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_authorships_bill_id_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], name=op.f('fk_bill_authorships_legislator_id_legislators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_authorships')),
    sa.UniqueConstraint('bill_id', 'legislator_id', name='uq_bill_authorships_bill_legislator')
    )
    op.create_index(op.f('ix_bill_authorships_deleted_at'), 'bill_authorships', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bill_authorships_sync_version'), 'bill_authorships', ['sync_version'], unique=False)
    op.create_table('bill_sponsoring_ministries',
    sa.Column('bill_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_sponsoring_ministries_bill_id_bills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_sponsoring_ministries'))
    )
    op.create_index(op.f('ix_bill_sponsoring_ministries_deleted_at'), 'bill_sponsoring_ministries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bill_sponsoring_ministries_sync_version'), 'bill_sponsoring_ministries', ['sync_version'], unique=False)
    op.create_table('bill_stages',
    sa.Column('bill_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_type', sa.Enum('FIRST_CONSTITUTIONAL_TRAMITE', 'SECOND_CONSTITUTIONAL_TRAMITE', 'THIRD_CONSTITUTIONAL_TRAMITE', 'MIXED_COMMISSION', 'CONSTITUTIONAL_TRIBUNAL', 'PROMULGATION', 'PUBLICATION', 'OTHER', name='stage_type', native_enum=False), nullable=False),
    sa.Column('chamber_id', sa.BigInteger(), nullable=True),
    sa.Column('committee_id', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('result', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_stages_bill_id_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chamber_id'], ['chambers.id'], name=op.f('fk_bill_stages_chamber_id_chambers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], name=op.f('fk_bill_stages_committee_id_committees'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_stages'))
    )
    op.create_index(op.f('ix_bill_stages_deleted_at'), 'bill_stages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bill_stages_sync_version'), 'bill_stages', ['sync_version'], unique=False)
    op.create_table('bill_topics',
    sa.Column('bill_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_topics_bill_id_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_bill_topics_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bill_id', 'topic_id', name=op.f('pk_bill_topics'))
    )
    op.create_table('bill_urgencies',
    sa.Column('bill_id', sa.BigInteger(), nullable=False),
    sa.Column('urgency_type', sa.Enum('SIMPLE', 'SUM', 'IMMEDIATE', name='urgency_type', native_enum=False), nullable=False),
    sa.Column('chamber_id', sa.BigInteger(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('withdrawal_date', sa.Date(), nullable=True),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_urgencies_bill_id_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chamber_id'], ['chambers.id'], name=op.f('fk_bill_urgencies_chamber_id_chambers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_urgencies'))
    )
    op.create_index(op.f('ix_bill_urgencies_deleted_at'), 'bill_urgencies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bill_urgencies_sync_version'), 'bill_urgencies', ['sync_version'], unique=False)
    op.create_table('committee_memberships',
    sa.Column('committee_id', sa.BigInteger(), nullable=False),
    sa.Column('legislator_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], name=op.f('fk_committee_memberships_committee_id_committees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], name=op.f('fk_committee_memberships_legislator_id_legislators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_committee_memberships'))
    )
    op.create_index(op.f('ix_committee_memberships_deleted_at'), 'committee_memberships', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_committee_memberships_sync_version'), 'committee_memberships', ['sync_version'], unique=False)
    op.create_table('legislator_terms',
    sa.Column('legislator_id', sa.BigInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('chamber_id', sa.BigInteger(), nullable=False),
    sa.Column('party_id', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('end_reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['chamber_id'], ['chambers.id'], name=op.f('fk_legislator_terms_chamber_id_chambers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], name=op.f('fk_legislator_terms_legislator_id_legislators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['political_parties.id'], name=op.f('fk_legislator_terms_party_id_political_parties'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_id'], ['legislative_periods.id'], name=op.f('fk_legislator_terms_period_id_legislative_periods'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legislator_terms'))
    )
    op.create_index(op.f('ix_legislator_terms_deleted_at'), 'legislator_terms', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_legislator_terms_sync_version'), 'legislator_terms', ['sync_version'], unique=False)
    op.create_table('legislator_voting_stats',
    sa.Column('legislator_id', sa.BigInteger(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('votes_for', sa.Integer(), nullable=False),
    sa.Column('votes_against', sa.Integer(), nullable=False),
    sa.Column('abstentions', sa.Integer(), nullable=False),
    sa.Column('absences', sa.Integer(), nullable=False),
    sa.Column('attendance_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('participation_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('inferred_bloc', sa.Enum('OFICIALISMO', 'OPOSICION', name='legislator_inferred_bloc', native_enum=False), nullable=True),
    sa.Column('lean_agreed', sa.Integer(), nullable=False),
    sa.Column('lean_contested', sa.Integer(), nullable=False),
    sa.Column('lean_seats', sa.Boolean(), nullable=False),
    sa.Column('discipline_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discipline_with', sa.Integer(), nullable=False),
    sa.Column('discipline_decided', sa.Integer(), nullable=False),
    sa.Column('stats_updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], name=op.f('fk_legislator_voting_stats_legislator_id_legislators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legislator_voting_stats')),
    sa.UniqueConstraint('legislator_id', name=op.f('uq_legislator_voting_stats_legislator_id'))
    )
    op.create_index(op.f('ix_legislator_voting_stats_deleted_at'), 'legislator_voting_stats', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_legislator_voting_stats_sync_version'), 'legislator_voting_stats', ['sync_version'], unique=False)
    op.create_table('parliamentary_appointments',
    sa.Column('legislator_id', sa.BigInteger(), nullable=False),
    sa.Column('chamber_id', sa.BigInteger(), nullable=False),
    sa.Column('bcn_appointment_uri', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['chamber_id'], ['chambers.id'], name=op.f('fk_parliamentary_appointments_chamber_id_chambers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], name=op.f('fk_parliamentary_appointments_legislator_id_legislators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parliamentary_appointments')),
    sa.UniqueConstraint('bcn_appointment_uri', name=op.f('uq_parliamentary_appointments_bcn_appointment_uri'))
    )
    op.create_index(op.f('ix_parliamentary_appointments_deleted_at'), 'parliamentary_appointments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_parliamentary_appointments_sync_version'), 'parliamentary_appointments', ['sync_version'], unique=False)
    op.create_table('bill_documents',
    sa.Column('bill_id', sa.BigInteger(), nullable=False),
    sa.Column('bill_stage_id', sa.BigInteger(), nullable=True),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_documents_bill_id_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bill_stage_id'], ['bill_stages.id'], name=op.f('fk_bill_documents_bill_stage_id_bill_stages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_documents'))
    )
    op.create_index(op.f('ix_bill_documents_deleted_at'), 'bill_documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bill_documents_sync_version'), 'bill_documents', ['sync_version'], unique=False)
    op.create_table('bill_events',
    sa.Column('bill_id', sa.BigInteger(), nullable=False),
    sa.Column('bill_stage_id', sa.BigInteger(), nullable=True),
    sa.Column('chamber_id', sa.BigInteger(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_events_bill_id_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bill_stage_id'], ['bill_stages.id'], name=op.f('fk_bill_events_bill_stage_id_bill_stages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chamber_id'], ['chambers.id'], name=op.f('fk_bill_events_chamber_id_chambers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_events'))
    )
    op.create_index(op.f('ix_bill_events_deleted_at'), 'bill_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bill_events_sync_version'), 'bill_events', ['sync_version'], unique=False)
    op.create_table('voting_sessions',
    sa.Column('bcn_id', sa.String(length=100), nullable=True),
    sa.Column('chamber_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('bill_id', sa.BigInteger(), nullable=True),
    sa.Column('bill_stage_id', sa.BigInteger(), nullable=True),
    sa.Column('voting_type', sa.Enum('GENERAL', 'PARTICULAR', 'SINGLE', 'OTHER', name='voting_type', native_enum=False), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('voting_date', sa.DateTime(), nullable=False),
    sa.Column('result', sa.Enum('APPROVED', 'REJECTED', 'TIE', name='voting_result', native_enum=False), nullable=True),
    sa.Column('votes_for', sa.Integer(), nullable=False),
    sa.Column('votes_against', sa.Integer(), nullable=False),
    sa.Column('abstentions', sa.Integer(), nullable=False),
    sa.Column('dispensed_count', sa.Integer(), nullable=False),
    sa.Column('absences', sa.Integer(), nullable=False),
    sa.Column('paired_count', sa.Integer(), nullable=False),
    sa.Column('quorum_required', sa.Integer(), nullable=True),
    sa.Column('quorum_type', sa.String(length=100), nullable=True),
    sa.Column('session_ref', sa.String(length=100), nullable=True),
    sa.Column('stage_label', sa.String(length=200), nullable=True),
    sa.Column('article_text', sa.Text(), nullable=True),
    sa.Column('constitutional_procedure_id', sa.Integer(), nullable=True),
    sa.Column('constitutional_procedure_label', sa.String(length=100), nullable=True),
    sa.Column('regulatory_procedure_id', sa.Integer(), nullable=True),
    sa.Column('regulatory_procedure_label', sa.String(length=100), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_voting_sessions_bill_id_bills'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bill_stage_id'], ['bill_stages.id'], name=op.f('fk_voting_sessions_bill_stage_id_bill_stages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chamber_id'], ['chambers.id'], name=op.f('fk_voting_sessions_chamber_id_chambers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['legislative_sessions.id'], name=op.f('fk_voting_sessions_session_id_legislative_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voting_sessions')),
    sa.UniqueConstraint('bcn_id', name=op.f('uq_voting_sessions_bcn_id'))
    )
    op.create_index(op.f('ix_voting_sessions_deleted_at'), 'voting_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_voting_sessions_sync_version'), 'voting_sessions', ['sync_version'], unique=False)
    op.create_table('votes',
    sa.Column('voting_session_id', sa.BigInteger(), nullable=False),
    sa.Column('legislator_id', sa.BigInteger(), nullable=False),
    sa.Column('vote', sa.Enum('FOR', 'AGAINST', 'ABSTAIN', 'PAIRED', 'DISPENSED', 'ABSENT', name='vote_choice', native_enum=False), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], name=op.f('fk_votes_legislator_id_legislators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voting_session_id'], ['voting_sessions.id'], name=op.f('fk_votes_voting_session_id_voting_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_votes')),
    sa.UniqueConstraint('voting_session_id', 'legislator_id', name='uq_votes_session_legislator')
    )
    op.create_index(op.f('ix_votes_deleted_at'), 'votes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_votes_sync_version'), 'votes', ['sync_version'], unique=False)
    op.create_table('voting_session_signals',
    sa.Column('voting_session_id', sa.BigInteger(), nullable=False),
    sa.Column('signal_type', sa.Enum('QUIEBRE_BLOQUE', 'DIVERGENCIA_CAMARAS', 'VOTACION_DIVIDIDA', 'ALTO_AUSENTISMO', name='signal_type', native_enum=False), nullable=False),
    sa.Column('severity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text("nextval('global_sync_version_seq')"), nullable=False),
    sa.ForeignKeyConstraint(['voting_session_id'], ['voting_sessions.id'], name=op.f('fk_voting_session_signals_voting_session_id_voting_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voting_session_signals')),
    sa.UniqueConstraint('voting_session_id', 'signal_type', name='uq_voting_session_signals_session_type')
    )
    op.create_index(op.f('ix_voting_session_signals_deleted_at'), 'voting_session_signals', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_voting_session_signals_signal_type'), 'voting_session_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_voting_session_signals_sync_version'), 'voting_session_signals', ['sync_version'], unique=False)
    op.create_index(op.f('ix_voting_session_signals_voting_session_id'), 'voting_session_signals', ['voting_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voting_session_signals_voting_session_id'), table_name='voting_session_signals')
    op.drop_index(op.f('ix_voting_session_signals_sync_version'), table_name='voting_session_signals')
    op.drop_index(op.f('ix_voting_session_signals_signal_type'), table_name='voting_session_signals')
    op.drop_index(op.f('ix_voting_session_signals_deleted_at'), table_name='voting_session_signals')
    op.drop_table('voting_session_signals')
    op.drop_index(op.f('ix_votes_sync_version'), table_name='votes')
    op.drop_index(op.f('ix_votes_deleted_at'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_voting_sessions_sync_version'), table_name='voting_sessions')
    op.drop_index(op.f('ix_voting_sessions_deleted_at'), table_name='voting_sessions')
    op.drop_table('voting_sessions')
    op.drop_index(op.f('ix_bill_events_sync_version'), table_name='bill_events')
    op.drop_index(op.f('ix_bill_events_deleted_at'), table_name='bill_events')
    op.drop_table('bill_events')
    op.drop_index(op.f('ix_bill_documents_sync_version'), table_name='bill_documents')
    op.drop_index(op.f('ix_bill_documents_deleted_at'), table_name='bill_documents')
    op.drop_table('bill_documents')
    op.drop_index(op.f('ix_parliamentary_appointments_sync_version'), table_name='parliamentary_appointments')
    op.drop_index(op.f('ix_parliamentary_appointments_deleted_at'), table_name='parliamentary_appointments')
    op.drop_table('parliamentary_appointments')
    op.drop_index(op.f('ix_legislator_voting_stats_sync_version'), table_name='legislator_voting_stats')
    op.drop_index(op.f('ix_legislator_voting_stats_deleted_at'), table_name='legislator_voting_stats')
    op.drop_table('legislator_voting_stats')
    op.drop_index(op.f('ix_legislator_terms_sync_version'), table_name='legislator_terms')
    op.drop_index(op.f('ix_legislator_terms_deleted_at'), table_name='legislator_terms')
    op.drop_table('legislator_terms')
    op.drop_index(op.f('ix_committee_memberships_sync_version'), table_name='committee_memberships')
    op.drop_index(op.f('ix_committee_memberships_deleted_at'), table_name='committee_memberships')
    op.drop_table('committee_memberships')
    op.drop_index(op.f('ix_bill_urgencies_sync_version'), table_name='bill_urgencies')
    op.drop_index(op.f('ix_bill_urgencies_deleted_at'), table_name='bill_urgencies')
    op.drop_table('bill_urgencies')
    op.drop_table('bill_topics')
    op.drop_index(op.f('ix_bill_stages_sync_version'), table_name='bill_stages')
    op.drop_index(op.f('ix_bill_stages_deleted_at'), table_name='bill_stages')
    op.drop_table('bill_stages')
    op.drop_index(op.f('ix_bill_sponsoring_ministries_sync_version'), table_name='bill_sponsoring_ministries')
    op.drop_index(op.f('ix_bill_sponsoring_ministries_deleted_at'), table_name='bill_sponsoring_ministries')
    op.drop_table('bill_sponsoring_ministries')
    op.drop_index(op.f('ix_bill_authorships_sync_version'), table_name='bill_authorships')
    op.drop_index(op.f('ix_bill_authorships_deleted_at'), table_name='bill_authorships')
    op.drop_table('bill_authorships')
    op.drop_index(op.f('ix_legislators_sync_version'), table_name='legislators')
    op.drop_index(op.f('ix_legislators_deleted_at'), table_name='legislators')
    op.drop_table('legislators')
    op.drop_index(op.f('ix_communes_sync_version'), table_name='communes')
    op.drop_index(op.f('ix_communes_deleted_at'), table_name='communes')
    op.drop_table('communes')
    op.drop_index(op.f('ix_bills_sync_version'), table_name='bills')
    op.drop_index(op.f('ix_bills_deleted_at'), table_name='bills')
    op.drop_table('bills')
    op.drop_table('regulation_stages')
    op.drop_index(op.f('ix_provinces_sync_version'), table_name='provinces')
    op.drop_index(op.f('ix_provinces_deleted_at'), table_name='provinces')
    op.drop_table('provinces')
    op.drop_index(op.f('ix_legislative_sessions_sync_version'), table_name='legislative_sessions')
    op.drop_index(op.f('ix_legislative_sessions_deleted_at'), table_name='legislative_sessions')
    op.drop_table('legislative_sessions')
    op.drop_index(op.f('ix_districts_sync_version'), table_name='districts')
    op.drop_index(op.f('ix_districts_deleted_at'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_committees_sync_version'), table_name='committees')
    op.drop_index(op.f('ix_committees_deleted_at'), table_name='committees')
    op.drop_table('committees')
    op.drop_index(op.f('ix_coalition_memberships_sync_version'), table_name='coalition_memberships')
    op.drop_index(op.f('ix_coalition_memberships_deleted_at'), table_name='coalition_memberships')
    op.drop_table('coalition_memberships')
    op.drop_table('circumscription_regions')
    op.drop_index(op.f('ix_bloc_affiliations_sync_version'), table_name='bloc_affiliations')
    op.drop_index(op.f('ix_bloc_affiliations_deleted_at'), table_name='bloc_affiliations')
    op.drop_table('bloc_affiliations')
    op.drop_index(op.f('ix_voting_window_aggregates_sync_version'), table_name='voting_window_aggregates')
    op.drop_index(op.f('ix_voting_window_aggregates_deleted_at'), table_name='voting_window_aggregates')
    op.drop_table('voting_window_aggregates')
    op.drop_index(op.f('ix_topics_sync_version'), table_name='topics')
    op.drop_index(op.f('ix_topics_deleted_at'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_regulations_sync_version'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_deleted_at'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_content_fingerprint'), table_name='regulations')
    op.drop_table('regulations')
    op.drop_index(op.f('ix_regions_sync_version'), table_name='regions')
    op.drop_index(op.f('ix_regions_deleted_at'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_political_parties_sync_version'), table_name='political_parties')
    op.drop_index(op.f('ix_political_parties_deleted_at'), table_name='political_parties')
    op.drop_table('political_parties')
    op.drop_index(op.f('ix_official_gazette_norms_sync_version'), table_name='official_gazette_norms')
    op.drop_index(op.f('ix_official_gazette_norms_deleted_at'), table_name='official_gazette_norms')
    op.drop_table('official_gazette_norms')
    op.drop_index(op.f('ix_legislative_periods_sync_version'), table_name='legislative_periods')
    op.drop_index(op.f('ix_legislative_periods_deleted_at'), table_name='legislative_periods')
    op.drop_table('legislative_periods')
    op.drop_table('ingestor_state')
    op.drop_index(op.f('ix_coalitions_sync_version'), table_name='coalitions')
    op.drop_index(op.f('ix_coalitions_deleted_at'), table_name='coalitions')
    op.drop_table('coalitions')
    op.drop_index(op.f('ix_client_sync_states_entity_type'), table_name='client_sync_states')
    op.drop_index(op.f('ix_client_sync_states_device_id'), table_name='client_sync_states')
    op.drop_table('client_sync_states')
    op.drop_index(op.f('ix_circumscriptions_sync_version'), table_name='circumscriptions')
    op.drop_index(op.f('ix_circumscriptions_deleted_at'), table_name='circumscriptions')
    op.drop_table('circumscriptions')
    op.drop_index(op.f('ix_change_logs_sync_version'), table_name='change_logs')
    op.drop_index(op.f('ix_change_logs_entity_type'), table_name='change_logs')
    op.drop_index(op.f('ix_change_logs_entity_id'), table_name='change_logs')
    op.drop_table('change_logs')
    op.drop_index(op.f('ix_chambers_sync_version'), table_name='chambers')
    op.drop_index(op.f('ix_chambers_deleted_at'), table_name='chambers')
    op.drop_table('chambers')
    op.execute(sa.schema.DropSequence(sa.Sequence('global_sync_version_seq')))
    # ### end Alembic commands ###
