"""add calendar_event bulletin_number

Revision ID: a03b709c50e7
Revises: e03d4c13e902
Create Date: 2026-07-04 21:53:16.268627
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a03b709c50e7"
down_revision = "e03d4c13e902"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calendar_events",
        sa.Column("bulletin_number", sa.String(length=50), nullable=True),
    )
    op.create_index(
        "ix_calendar_events_pending_bulletin",
        "calendar_events",
        ["bulletin_number"],
        unique=False,
        postgresql_where="bill_id IS NULL AND bulletin_number IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_calendar_events_pending_bulletin",
        table_name="calendar_events",
        postgresql_where="bill_id IS NULL AND bulletin_number IS NOT NULL",
    )
    op.drop_column("calendar_events", "bulletin_number")
    # ### end Alembic commands ###
