"""add_bill_full_text

Revision ID: be659542bab2
Revises: ccd0c7e0865a
Create Date: 2026-04-22 20:59:33.622918
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'be659542bab2'
down_revision = 'ccd0c7e0865a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('full_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'full_text')
    # ### end Alembic commands ###
